export const Dados = [
  {
    id: 1,
    tipo: 1,
    nome: "João Pedro",
    status: "Concluído",
    aprovacao: "Reprovado",
    dataAprovacao: "06/03/2025 - 12:30h",
    data: "05/03/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: "05/03/2025",
    horaConclusao: "22:40",
    justificativa: null,
    localizacao: {
      latitude: -20.315000,
      longitude: -40.305000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 2,
    tipo: 1,
    nome: "João Pedro",
    status: "Concluído",
    aprovacao: "Reprovado",
    dataAprovacao: "06/03/2025 - 12:30h",
    data: "05/03/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: "05/03/2025",
    horaConclusao: "22:40",
    justificativa: {
      imagem: require("./assets/images/atestado.png"),
      descricao: "Descrição não disponível",
      motivo: "Atestado"
    },
    localizacao: {
      latitude: -20.325000,
      longitude: -40.295000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 3,
    tipo: 1,
    nome: "João Pedro",
    status: "Concluído",
    aprovacao: "Aprovado",
    dataAprovacao: "06/03/2025 - 12:30h",
    data: "05/04/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: "05/03/2025",
    horaConclusao: "22:40",
    justificativa: null,
    localizacao: {
      latitude: -20.305000,
      longitude: -40.315000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 4,
    tipo: 1,
    nome: "João Pedro",
    status: "Concluído",
    aprovacao: "Aprovado",
    dataAprovacao: "06/03/2025 - 12:30h",
    data: "05/04/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: "05/03/2025",
    horaConclusao: "22:40",
    justificativa: {
      imagem: require("./assets/images/atestado.png"),
      descricao: "Descrição não disponível",
      motivo: "Atestado"
    },
    localizacao: {
      latitude: -20.335000,
      longitude: -40.285000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 5,
    tipo: 1,
    nome: "João Pedro",
    status: "Pendente",
    aprovacao: null,
    dataAprovacao: null,
    data: "05/05/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: null,
    horaConclusao: null,
    justificativa: null,
    localizacao: {
      latitude: -20.300000,
      longitude: -40.320000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 6,
    tipo: 1,
    nome: "João Pedro",
    status: "Aberto",
    aprovacao: null,
    dataAprovacao: null,
    data: "05/05/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: null,
    horaConclusao: null,
    justificativa: null,
    localizacao: {
      latitude: -20.340000,
      longitude: -40.280000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 7,
    tipo: 2,
    nome: "João Pedro",
    status: "Grave",
    aprovacao: "Reprovado",
    dataAprovacao: "06/03/2025 - 12:30h",
    data: "05/06/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: "05/03/2025",
    horaConclusao: "22:40",
    justificativa: null,
    localizacao: {
      latitude: -20.350000,  // Ponto mais ao sul
      longitude: -40.330000, // Ponto mais a oeste
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 8,
    tipo: 2,
    nome: "João Pedro",
    status: "Leve",
    aprovacao: "Reprovado",
    dataAprovacao: "06/03/2025 - 12:30h",
    data: "05/06/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: "05/03/2025",
    horaConclusao: "22:40",
    justificativa: {
      imagem: require("./assets/images/atestado.png"),
      descricao: "Descrição não disponível",
      motivo: "Atestado"
    },
    localizacao: {
      latitude: -20.290000,  // Ponto mais ao norte
      longitude: -40.270000, // Ponto mais a leste
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 9,
    tipo: 2,
    nome: "João Pedro",
    status: "Nenhum",
    aprovacao: "Aprovado",
    dataAprovacao: "06/03/2025 - 12:30h",
    data: "05/07/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: "05/03/2025",
    horaConclusao: "22:40",
    justificativa: null,
    localizacao: {
      latitude: -20.310000,
      longitude: -40.310000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 10,
    tipo: 2,
    nome: "João Pedro",
    status: "Grave",
    aprovacao: "Aprovado",
    dataAprovacao: "06/03/2025 - 12:30h",
    data: "05/07/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: "05/03/2025",
    horaConclusao: "22:40",
    justificativa: {
      imagem: require("./assets/images/atestado.png"),
      descricao: "Descrição não disponível",
      motivo: "Atestado"
    },
    localizacao: {
      latitude: -20.320000,
      longitude: -40.290000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 11,
    tipo: 2,
    nome: "João Pedro",
    status: "Leve",
    aprovacao: null,
    dataAprovacao: null,
    data: "05/08/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: null,
    horaConclusao: null,
    justificativa: null,
    localizacao: {
      latitude: -20.300500,
      longitude: -40.315000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  },
  {
    id: 12,
    tipo: 2,
    nome: "Nenhum",
    status: "Aberto",
    aprovacao: null,
    dataAprovacao: null,
    data: "05/08/2025",
    hora: "13:40",
    peso: "320 g",
    Material: "Poeira de Sílica",
    causa_queda: "Vibração Excessiva",
    equipamento: "Tremonha Vibratória",
    descricao_audio: "Intermitente",
    dataConclusao: null,
    horaConclusao: null,
    justificativa: null,
    localizacao: {
      latitude: -20.330000,
      longitude: -40.295000,
      local: "Zona de Carga",
      origem: "Funil Principal",
      origem_detalhado: "Silo 9",
      destino_final: "Separador de Ar",
    },
    foto: [require("./assets/images/ocorrencias.png")],
    data_fotos_registradas: "06/03/2025",
    hora_fotos_registradas: "07:30",
  }
];